# Generated by Django 5.1.4 on 2026-05-24 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('url_facebook_post', models.URLField(blank=True, help_text='URL del post original si vino de FB', null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado')], default='activo', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Ciclo de Venta',
                'verbose_name_plural': 'Ciclos de Venta',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('talla_tipo', models.CharField(choices=[('unica', 'Talla Única'), ('por_talla', 'Por Talla')], default='unica', max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotada', 'Agotada'), ('archivada', 'Archivada')], default='disponible', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prendas', to='catalogo.cicloventa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PrendaVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('talla', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.prenda')),
            ],
            options={
                'verbose_name': 'Variante de Prenda',
                'verbose_name_plural': 'Variantes de Prenda',
                'ordering': ['color', 'talla'],
                'unique_together': {('prenda', 'color', 'talla')},
            },
        ),
    ]
