# Generated by Django 6.0.5 on 2026-05-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='foto_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
