# Generated by Django 6.0.5 on 2026-05-24 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_prenda_foto_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrendaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='prendas/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.prenda')),
            ],
            options={
                'verbose_name': 'Imagen de Prenda',
                'verbose_name_plural': 'Imágenes de Prenda',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
    ]
