# Generated by Django 6.0.5 on 2026-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_prendaimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloventa',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, help_text='Fecha para publicarse automáticamente', null=True),
        ),
        migrations.AlterField(
            model_name='cicloventa',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('activo', 'Activo'), ('cerrado', 'Cerrado')], default='activo', max_length=20),
        ),
    ]
