# Generated by Django 6.0.5 on 2026-05-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_cicloventa_fecha_programada_alter_cicloventa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloventa',
            name='mensaje_facebook',
            field=models.TextField(blank=True, help_text='Mensaje personalizado para Facebook', null=True),
        ),
    ]
