# Generated by Django 6.0.5 on 2026-05-26 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_cicloventa_mensaje_facebook'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenda',
            options={'ordering': ['-fecha_ultima_carga'], 'verbose_name': 'Prenda', 'verbose_name_plural': 'Prendas'},
        ),
        migrations.AddField(
            model_name='prenda',
            name='fecha_ultima_carga',
            field=models.DateTimeField(auto_now=True, help_text='Se actualiza cada vez que se sube stock a esta prenda. Usado para el filtro "nuevas de hoy".', verbose_name='Última vez cargada'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
                'unique_together': {('tenant', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='prenda',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prendas', to='catalogo.categoria', verbose_name='Categoría'),
        ),
    ]
