# Generated by Django 6.0.5 on 2026-05-27 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_add_categoria_and_fecha_ultima_carga'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPredefinido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores_predefinidos', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Color Predefinido',
                'ordering': ['nombre'],
                'unique_together': {('tenant', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='NombrePrendaPredefinido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombres_prendas_predefinidos', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Nombre de Prenda Predefinido',
                'ordering': ['nombre'],
                'unique_together': {('tenant', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='TallaPredefinida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas_predefinidas', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Talla Predefinida',
                'ordering': ['nombre'],
                'unique_together': {('tenant', 'nombre')},
            },
        ),
    ]
