# Generated by Django 6.0.5 on 2026-05-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_colorpredefinido_nombreprendapredefinido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Precio de Compra/Costo'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio de Venta'),
        ),
    ]
