# Generated by Django on 2026-05-28

from django.db import migrations

def renombrar_prendas(apps, schema_editor):
    Prenda = apps.get_model('catalogo', 'Prenda')
    for p in Prenda.objects.filter(nombre__startswith='Recuperado'):
        nuevo_nombre = p.nombre.replace('Recuperado - ', 'Prenda ').replace('Recuperado: ', 'Prenda ')
        p.nombre = nuevo_nombre
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_prenda_precio_compra_alter_prenda_precio'),
    ]

    operations = [
        migrations.RunPython(renombrar_prendas),
    ]
