# Generated by Django 6.0.5 on 2026-06-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_renombrar_recuperados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('vendida', 'Vendida')], default='disponible', max_length=20),
        ),
    ]
