# Generated by Django 6.0.5 on 2026-06-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_alter_prenda_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prendaimagen',
            name='color',
            field=models.CharField(blank=True, help_text='Color asociado a esta foto', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('vendida', 'Vendida'), ('agotada', 'Agotada'), ('archivada', 'Archivada')], default='disponible', max_length=20),
        ),
    ]
