# Generated by Django 6.0.5 on 2026-06-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_prendaimagen_color_alter_prenda_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la prenda', null=True),
        ),
    ]
