# Generated by Django 6.0.5 on 2026-06-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_prenda_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, default='Sparkles', max_length=50, null=True, verbose_name='Ícono'),
        ),
    ]
