# Generated by Django 6.0.5 on 2026-06-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_categoria_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpredefinido',
            name='hex_code',
            field=models.CharField(blank=True, help_text='Código HEX del color', max_length=7, null=True),
        ),
    ]
