# Generated by Django 5.1.4 on 2026-06-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_colorpredefinido_hex_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('vendida', 'Vendida'), ('agotada', 'Agotada'), ('archivada', 'Archivada')], db_index=True, default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
