# Generated by Django 6.0.5 on 2026-06-03 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0010_alter_prenda_estado'),
        ('core', '0002_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='catalogo.prenda')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_interes', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Consulta de Interés',
                'verbose_name_plural': 'Consultas de Interés',
                'ordering': ['-fecha'],
            },
        ),
    ]
