server {
    listen 80;
    server_name 157.230.93.24;

    client_max_body_size 50M;

    location = /favicon.ico { access_log off; log_not_found off; }

    # Backend Django Static files
    location /static/ {
        alias /var/www/mindylu/backend/staticfiles/;
    }
    
    location /media/ {
        alias /var/www/mindylu/backend/media/;
    }

    # Proxy to Django API
    location /api/ {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    location /admin/ {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    # Serve React Frontend
    location / {
        root /var/www/mindylu/frontend/dist;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
