#!/bin/bash
TARGET="/var/www/mindylu"
GIT_DIR="/var/repo/mindylu.git"
BRANCH="master"

while read oldrev newrev ref
do
    # Only deploy master branch
    if [[ $ref = refs/heads/$BRANCH ]]; then
        echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
        
        # Checkout code
        mkdir -p $TARGET
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH

        # Backend setup
        echo "Setting up Backend..."
        cd $TARGET/backend
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        python manage.py makemigrations
        python manage.py migrate
        python manage.py collectstatic --noinput
        
        # Setup Gunicorn/ASGI service
        echo "Updating Gunicorn service..."
        cp $TARGET/gunicorn.service /etc/systemd/system/gunicorn.service
        systemctl daemon-reload
        systemctl restart gunicorn

        # Setup Nginx
        echo "Updating Nginx configuration..."
        cp $TARGET/mindylu.conf /etc/nginx/sites-available/mindylu
        # Enforce symlink
        ln -sf /etc/nginx/sites-available/mindylu /etc/nginx/sites-enabled/mindylu
        systemctl reload nginx

        # Frontend setup
        echo "Setting up Frontend..."
        cd $TARGET/frontend
        npm install
        npm run build

        echo "Deployment completed successfully!"
    else
        echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
    fi
done
