# Generated by Django 6.0.5 on 2026-05-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend')], max_length=20)),
                ('mensaje', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Error',
                'verbose_name_plural': 'Logs de Errores',
                'ordering': ['-fecha'],
            },
        ),
    ]
