# Generated by Django 6.0.5 on 2026-06-03 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marquesina_texto', models.CharField(default='NUEVA COLECCIÓN 2025 • NUEVA COLECCIÓN 2025 • NUEVA COLECCIÓN 2025', max_length=255, verbose_name='Texto de la marquesina')),
                ('banner_imagen', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Imagen del Banner')),
                ('banner_titulo', models.CharField(default='Moda femenina seleccionada especialmente para ti', max_length=255, verbose_name='Título del Banner')),
                ('banner_subtitulo', models.TextField(default='Prendas únicas, elegantes y exclusivas.\nCada pieza seleccionada con amor y estilo.', verbose_name='Subtítulo del Banner')),
                ('whatsapp_numero', models.CharField(blank=True, default='', max_length=20, verbose_name='Número de WhatsApp')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuraciones de Tienda',
            },
        ),
    ]
