# Generated by Django 6.0.5 on 2026-06-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuraciontienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontienda',
            name='marquesina_velocidad',
            field=models.IntegerField(default=25, verbose_name='Velocidad de Marquesina (segundos)'),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='tienda_nombre',
            field=models.CharField(default='MindyLu', max_length=100, verbose_name='Nombre de la Tienda (UI)'),
        ),
        migrations.AlterField(
            model_name='configuraciontienda',
            name='whatsapp_numero',
            field=models.CharField(blank=True, default='56972677820', max_length=20, verbose_name='Número de WhatsApp'),
        ),
    ]
