# Generated by Django 6.0.5 on 2026-06-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_avatar_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontienda',
            name='polaroid_1_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Imagen Polaroid 1'),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='polaroid_2_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Imagen Polaroid 2'),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='polaroid_3_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Imagen Polaroid 3'),
        ),
    ]
