# Generated by Django 6.0.5 on 2026-06-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuraciontienda_polaroid_1_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontienda',
            name='banner_titulo_cursiva',
            field=models.CharField(blank=True, default='Tu Mindy Lu.', max_length=255, verbose_name='Título Cursiva del Banner'),
        ),
    ]
