# Generated by Django 6.0.5 on 2026-06-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuraciontienda_banner_titulo_cursiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontienda',
            name='envios_texto',
            field=models.TextField(default='Envíos a Viña del Mar $2500\nValparaíso $2500\nCurauma Placilla $2500\nQuilpué Villa Alemana $2500\n\nRegiones envío por Starken por pagar', verbose_name='Información de Envíos'),
        ),
    ]
