# Generated by Django 5.1.4 on 2026-06-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontienda',
            name='sugerencia_mensaje_bottom',
            field=models.TextField(default='¿Te gusta? 💕', verbose_name='Texto inferior de sugerencia'),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='sugerencia_mensaje_top',
            field=models.TextField(default='¡Hola linda! Mira esta opción hermosa que tengo disponible 😍', verbose_name='Texto superior de sugerencia'),
        ),
    ]
