# Generated by Django 5.1.4 on 2026-06-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_configuraciontienda_sugerencia_mensaje_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontienda',
            name='bot_mensaje_bienvenida',
            field=models.TextField(default='¡Hola, hermosa! 👋 Soy LuBot. ¿En qué te puedo ayudar hoy?', verbose_name='Mensaje Bienvenida Bot'),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='bot_opcion_1',
            field=models.CharField(default='¿Hacen entregas por delivery?', max_length=150, verbose_name='Opción 1 Bot'),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='bot_opcion_2',
            field=models.CharField(default='Quiero preguntar por prendas', max_length=150, verbose_name='Opción 2 Bot'),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='bot_opcion_3',
            field=models.CharField(default='Quiero hablar directo con Lu 💕', max_length=150, verbose_name='Opción 3 Bot'),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='bot_respuesta_1',
            field=models.TextField(default='¡Hola Linda! Sí, hacemos envíos a todo Chile vía Starken o Chilexpress por pagar. Además, tenemos entregas presenciales en puntos céntricos coordinados previamente. ¿Te gustaría saber algo más?', verbose_name='Respuesta 1 Bot'),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='bot_respuesta_2',
            field=models.TextField(default='¡Me encantan! Todas nuestras prendas están en el catálogo. Si buscas tallas o colores específicos, fíjate en los detalles de cada producto. Algunas prendas son exclusivas y de stock limitado. ¡Si quieres ver algo más, dímelo!', verbose_name='Respuesta 2 Bot'),
        ),
        migrations.AlterField(
            model_name='configuraciontienda',
            name='whatsapp_numero',
            field=models.CharField(blank=True, default='56933075784', max_length=20, verbose_name='Número de WhatsApp'),
        ),
    ]
