# Generated by Django 6.0.5 on 2026-05-24 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, help_text='Necesario para WhatsApp', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('perfil_facebook', models.URLField(blank=True, help_text='URL del perfil si compró por FB', null=True)),
                ('perfil_instagram', models.URLField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Ej: Es mañosa con las tallas, prefiere envíos los viernes...', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientas', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Clienta',
                'verbose_name_plural': 'Clientas',
                'ordering': ['nombre'],
                'unique_together': {('tenant', 'telefono')},
            },
        ),
    ]
