# Generated by Django 6.0.5 on 2026-06-12 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientas', '0001_initial'),
        ('cuentas', '0002_cuentabancaria_limite_mensual_transferencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienta',
            name='cuenta_asignada',
            field=models.ForeignKey(blank=True, help_text='Cuenta bancaria a la que debe depositar esta clienta por defecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientas_asignadas', to='cuentas.cuentabancaria'),
        ),
    ]
