# Generated by Django 6.0.5 on 2026-05-24 03:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(max_length=50)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('rut_titular', models.CharField(max_length=20)),
                ('nombre_titular', models.CharField(max_length=100)),
                ('email_notificacion', models.EmailField(blank=True, max_length=254)),
                ('limite_mensual_ingresos', models.IntegerField(default=4000000)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='core.tenant')),
            ],
            options={
                'db_table': 'cuenta_bancaria',
                'unique_together': {('tenant', 'numero_cuenta', 'banco')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cuentas.cuentabancaria')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'movimiento_cuenta',
            },
        ),
    ]
