# Generated by Django 6.0.5 on 2026-05-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='limite_mensual_transferencias',
            field=models.IntegerField(default=50),
        ),
    ]
