# Generated by Django 6.0.5 on 2026-06-12 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_configuraciontienda_envios_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(blank=True, help_text='Nombre de la instancia en Evolution API', max_length=100, null=True)),
                ('instance_id', models.CharField(blank=True, max_length=100, null=True)),
                ('connection_status', models.CharField(default='DISCONNECTED', max_length=50)),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Configuración de WhatsApp',
                'verbose_name_plural': 'Configuraciones de WhatsApp',
            },
        ),
    ]
