# Generated by Django 6.0.5 on 2026-06-12 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuraciontienda_envios_texto'),
        ('integraciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='connection_status',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='instance_id',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='instance_name',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='qr_code_base64',
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='access_token',
            field=models.TextField(blank=True, help_text='Token Permanente del Usuario de Sistema', null=True),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='phone_number_id',
            field=models.CharField(blank=True, help_text='ID del Número de Teléfono en Meta', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='waba_id',
            field=models.CharField(blank=True, help_text='ID de la Cuenta de WhatsApp Business', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', models.CharField(max_length=50)),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('unread_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wam_id', models.CharField(help_text='WhatsApp Message ID', max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Entrante'), ('OUTBOUND', 'Saliente')], max_length=10)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='integraciones.conversacion')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_at'],
            },
        ),
    ]
