# Generated by Django 6.0.5 on 2026-06-13 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuraciontienda_envios_texto'),
        ('integraciones', '0002_remove_whatsappconfig_connection_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaRespuestaBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabras_clave', models.CharField(help_text='Palabras o frases separadas por comas (ej: horario, donde estan, direccion)', max_length=500)),
                ('respuesta', models.TextField(help_text='Respuesta que enviará el bot cuando detecte alguna de las palabras clave')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_bot', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Regla de Respuesta Bot',
                'verbose_name_plural': 'Reglas de Respuesta Bot',
                'ordering': ['-created_at'],
            },
        ),
    ]
