# Generated by Django 5.1.4 on 2026-06-14 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pushsubscription'),
        ('integraciones', '0003_reglarespuestabot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: 🏦 Datos Bancarios', max_length=50)),
                ('mensaje', models.TextField(help_text='El mensaje que se enviará al cliente')),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_rapidas', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Respuesta Rápida',
                'verbose_name_plural': 'Respuestas Rápidas',
                'ordering': ['orden', 'created_at'],
            },
        ),
    ]
