# Generated by Django 5.1.4 on 2026-06-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0004_respuestarapida'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='plataforma',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook Messenger')], default='whatsapp', max_length=20),
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='wam_id',
            new_name='external_id',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='external_id',
            field=models.CharField(help_text='WhatsApp wam_id o Facebook message_id', max_length=255, unique=True),
        ),
    ]
