# Generated by Django 6.0.5 on 2026-05-24 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientas', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('apartado', 'Apartado (Pendiente de pago/entrega)'), ('pagado', 'Pagado (Listo para entregar)'), ('entregado', 'Entregado y Finalizado'), ('cancelado', 'Cancelado')], default='apartado', max_length=20)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_acordada', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('clienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='clientas.clienta')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.PositiveIntegerField(help_text='Precio de la prenda al momento de venderla')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.prendavariante')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
        migrations.CreateModel(
            name='PuntoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_entrega', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Punto de Entrega',
                'verbose_name_plural': 'Puntos de Entrega',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='punto_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.puntoentrega'),
        ),
        migrations.CreateModel(
            name='EntregaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_estimada', models.TimeField(blank=True, help_text='Ej: 14:00 hrs', null=True)),
                ('recordatorios_enviados', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_diarias', to='core.tenant')),
                ('pedidos', models.ManyToManyField(related_name='rutas_entrega', to='pedidos.pedido')),
                ('punto_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.puntoentrega')),
            ],
            options={
                'verbose_name': 'Entrega Diaria',
                'verbose_name_plural': 'Entregas Diarias',
                'ordering': ['-fecha', 'hora_estimada'],
                'unique_together': {('tenant', 'fecha', 'punto_entrega')},
            },
        ),
    ]
