# Generated by Django 6.0.5 on 2026-06-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('apartado', 'Apartado'), ('por_pagar', 'Por Pagar'), ('pagado', 'Pagado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='apartado', max_length=20),
        ),
    ]
