# Generated by Django 5.1.4 on 2026-06-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('apartado', 'Apartado'), ('por_pagar', 'Por Pagar'), ('pagado', 'Pagado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='apartado', max_length=20),
        ),
    ]
