# Generated by Django 5.1.4 on 2026-06-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_configuraciontienda_bot_mensaje_bienvenida_and_more'),
        ('pedidos', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puntoentrega',
            unique_together={('tenant', 'nombre')},
        ),
    ]
