# Generated by Django 5.1.4 on 2026-06-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_estado_and_more'),
        ('pedidos', '0004_alter_puntoentrega_unique_together'),
    ]

    operations = [
    ]
